/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package messenger.Ui;

import messenger.dataAkun.Kontak;

/**
 *
 * @author eko
 */
public class jInternalFrameKontak extends javax.swing.JInternalFrame {

    /**
     * Creates new form jInternalFrameKontak
     */
    Kontak mKo=new Kontak();
    public jInternalFrameKontak() {
        initComponents();
        txtNamaTeman.setText(mKo.getNameTeman());
        txtUsrnameteman.setText(mKo.getUsernameTeman());
        jTextStatus.setText(mKo.getStatus());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPaneKontak = new javax.swing.JDesktopPane();
        jLNamaTeman = new javax.swing.JLabel();
        txtNamaTeman = new javax.swing.JTextField();
        txtUsrnameteman = new javax.swing.JTextField();
        jLNamaUsrName = new javax.swing.JLabel();
        btnKirimPesan = new javax.swing.JButton();
        btnVoiceCall = new javax.swing.JButton();
        btnVideoCall = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextStatus = new javax.swing.JTextArea();
        jLabelStatus = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Kontak Anda");

        jDesktopPaneKontak.setBackground(new java.awt.Color(204, 204, 204));
        jDesktopPaneKontak.setToolTipText("");
        jDesktopPaneKontak.setAutoscrolls(true);

        jLNamaTeman.setText("Nama Teman");

        jLNamaUsrName.setText("Username");

        btnKirimPesan.setText("Kirim Pesan");

        btnVoiceCall.setText("Voice Call");

        btnVideoCall.setText("Video Call");

        jTextStatus.setColumns(20);
        jTextStatus.setRows(5);
        jScrollPane1.setViewportView(jTextStatus);

        jLabelStatus.setText("Status");

        javax.swing.GroupLayout jDesktopPaneKontakLayout = new javax.swing.GroupLayout(jDesktopPaneKontak);
        jDesktopPaneKontak.setLayout(jDesktopPaneKontakLayout);
        jDesktopPaneKontakLayout.setHorizontalGroup(
            jDesktopPaneKontakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPaneKontakLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPaneKontakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPaneKontakLayout.createSequentialGroup()
                        .addGroup(jDesktopPaneKontakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLNamaTeman)
                            .addComponent(jLNamaUsrName)
                            .addComponent(jLabelStatus))
                        .addGap(34, 34, 34)
                        .addGroup(jDesktopPaneKontakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUsrnameteman, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNamaTeman, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jDesktopPaneKontakLayout.createSequentialGroup()
                        .addComponent(btnKirimPesan)
                        .addGap(18, 18, 18)
                        .addComponent(btnVoiceCall, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnVideoCall, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        jDesktopPaneKontakLayout.setVerticalGroup(
            jDesktopPaneKontakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPaneKontakLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPaneKontakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNamaTeman)
                    .addComponent(txtNamaTeman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPaneKontakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNamaUsrName)
                    .addComponent(txtUsrnameteman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDesktopPaneKontakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelStatus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addGroup(jDesktopPaneKontakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKirimPesan)
                    .addComponent(btnVoiceCall)
                    .addComponent(btnVideoCall))
                .addGap(124, 124, 124))
        );
        jDesktopPaneKontak.setLayer(jLNamaTeman, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneKontak.setLayer(txtNamaTeman, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneKontak.setLayer(txtUsrnameteman, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneKontak.setLayer(jLNamaUsrName, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneKontak.setLayer(btnKirimPesan, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneKontak.setLayer(btnVoiceCall, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneKontak.setLayer(btnVideoCall, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneKontak.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneKontak.setLayer(jLabelStatus, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(jDesktopPaneKontak, java.awt.BorderLayout.LINE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKirimPesan;
    private javax.swing.JButton btnVideoCall;
    private javax.swing.JButton btnVoiceCall;
    private javax.swing.JDesktopPane jDesktopPaneKontak;
    private javax.swing.JLabel jLNamaTeman;
    private javax.swing.JLabel jLNamaUsrName;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextStatus;
    private javax.swing.JTextField txtNamaTeman;
    private javax.swing.JTextField txtUsrnameteman;
    // End of variables declaration//GEN-END:variables
}
